/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import IO.BioFormats.BioFormatsImg;
import Process.Segmentation.MultiThreadedWatershed;
import UIClasses.LayerPanel;
import ij.ImagePlus;
import java.util.Properties;
import params.DefaultParams;
import static params.DefaultParams.SEG_THRESH_LABEL;

/**
 *
 * @author David Barry <david.barry at crick dot ac dot uk>
 */
public class SegmentationPanel extends LayerPanel {

    /**
     * Creates new form SegmentationPanel
     */
    public SegmentationPanel() {
        this(null, null, null);
    }

    public SegmentationPanel(Properties props, BioFormatsImg img, MultiThreadedWatershed process) {
        super(props, img, process);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        previewButton = new javax.swing.JButton();
        thresholdLabel = new javax.swing.JLabel();
        thresholdTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        previewButton.setText("Preview");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(previewButton, gridBagConstraints);

        thresholdLabel.setText(SEG_THRESH_LABEL);
        thresholdLabel.setLabelFor(thresholdTextField);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(thresholdLabel, gridBagConstraints);

        thresholdTextField.setText("0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(thresholdTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        setVariables();

        String[] propLabels = new String[]{DefaultParams.SERIES_SELECT_LABEL,
            DefaultParams.SEG_CHAN_SELECT_LABEL,
            DefaultParams.SEG_THRESH_LABEL,
            DefaultParams.FILT_RAD_XY_LABEL,
            DefaultParams.FILT_RAD_Z_LABEL};

        process.setup(img, props, propLabels);
        process.start();
        try {
            process.join();
        } catch (InterruptedException e) {
            return;
        }
        ImagePlus imp = process.getOutput();
        imp.resetDisplayRange();
        imp.show();
    }//GEN-LAST:event_previewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton previewButton;
    private javax.swing.JLabel thresholdLabel;
    private javax.swing.JTextField thresholdTextField;
    // End of variables declaration//GEN-END:variables
}
